name: fold_pokedex
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  cupertino_icons: ^1.0.9
  cupertino_ui: ^1.0.2
  dio: ^5.11.1
  equatable: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  intl: ^0.20.3
  material_ui: ^1.2.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^11.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/  
